command_timeout = 10000

add_newline = false

[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format = " ğŸ•™ $duration($style)\n"

[battery]
disabled = true

[directory]
style = "cyan bold"

[git_branch]
symbol = "î‚  "
format = "[$symbol$branch]($style) "
[git_status]
disabled = true

[conda]
symbol = "ğŸ“¦ "
format = "[$symbol$environment](green bold)"
ignore_base = true

[docker_context]
symbol = "ğŸ³ "
style = "blue bold"
